server:
  port: 80
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.188.128:8848
    gateway:
      discovery:
        locator:
          enabled: true  #允许使用注册发现来进行服务转发
      routes:
        - id: service-product-router001
          uri: lb://service-product
          predicates:
            - Path=/*/product/**,/admin/product2/test/*
        - id: web-all-router002
          uri: lb://web-all
          predicates:
            - Host=item.omall.com,www.omall.com
