server:
  port: 8202
spring:
  application:
    name: service-item
  profiles:
    active: dev #激活dev开发环境
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.188.128:8848
    sentinel:
      transport:
        dashboard: http://192.168.188.128:8858
  zipkin:
    base-url: http://192.168.188.128:9411
    discovery-client-enabled: false
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  redis:
    host: 192.168.188.128
    port: 6379
    database: 0
    timeout: 5000 #连接超时时间单位是毫秒
    password:
    lettuce:
      pool:
        max-active: 20 #最大活动连接数
        max-wait: 30000
        max-idle: 5 #最大空闲连接数
        min-idle: 1 #最小空闲连接

#ribbon:
#  ReadTimeout: 4000
#  ConnectTimeout: 4000
feign:
  sentinel:
    enabled: true #开启熔断器使用sentinel
  client:
    config:
      default:
        readTimeout: 4000 #读超时时间 单位毫秒
        connectTimeout: 3000 #连接超时时间 单位毫秒
logging:
  level:
    com:
      offcn:
        product:
          client: debug