mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml  #指定mybatis映射文件所在目录
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #启用mybatis-plus的日志输出

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.188.128:3306/omall_product?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1  #测试连接是否有效
      maximum-pool-size: 100 #连接池最大连接数
      minimum-idle: 10 #最小空闲连接数
      connection-timeout: 60000 #等待获取连接超时时间
      idle-timeout: 50000 #空闲连接最大等待时间
      max-lifetime: 600000 #连接的最大生命周期
      pool-name: UJIUYEPool
    type: com.zaxxer.hikari.HikariDataSource
  zipkin:
    base-url: http://192.168.188.128:9411
    discovery-client-enabled: false
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  cloud:
    sentinel:
      transport:
        dashboard: http://192.168.188.128:8858
  rabbitmq:
    host: 192.168.188.128
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.188.128
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
    timeout: 3000 #和redis建立连接超时时间
  jackson:
    time-zone: GMT+8  #设置json进行日期时间格式化时区 东八区
    date-format: yyyy-MM-dd HH:mm:ss #设置json格式化日期时间对象输出格式

#自定义配置
fileServer:
  url: http://192.168.188.128:8080/ # fastDFS 分布式文件系统的 ip:port